spring:
  application:
    name: cloud-provider
  cloud:
    stream:
      bindings:
        input:
          destination: provider
          group: cloud-provider
          consumer:
            autoCommitOffset: true
            concurrency: 7
        output:
          destination: order-topic