spring:
  application:
    name: cloud-consumer
  cloud:
    stream:
      bindings:
        input:
          destination: consumer
          group: cloud-consumer
          consumer:
            autoCommitOffset: true
            concurrency: 7
        output:
          destination: order-topic