spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show-sql: true
    properties:
      hibernate.hbm2ddl.auto: none
      hibernate.query.substitutions: true 'T', false 'F'
      hibernate.jdbc.batch_size: 30
      hibernate.format_sql: true
      org.hibernate.envers.auditTableSuffix: _AUD
      org.hibernate.envers.revisionTypeFieldName: REV_TYPE
      org.hibernate.envers.doNotAuditOptimisticLockingField: false
#      hibernate.ejb.interceptor:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
#      hibernate.cache.use_second_level_cache: true
#      hibernate.cache.use_query_cache: false
#      hibernate.generate_statistics: false
#      hibernate.cache.region.factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
#      hibernate.cache.hazelcast.instance_name: Ehazelcast
#      hibernate.cache.use_minimal_puts: true
#      hibernate.cache.hazelcast.use_lite_member: true
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
