spring:
  cloud:
    nacos:
      discovery:
        group: APPLICATION_GROUP
        server-addr: ${spring.nacos.server-addr}
        username: ${spring.cloud.seeyon.config.username}
        password: ${spring.cloud.seeyon.config.password}
        namespace: ${spring.cloud.seeyon.config.namespace}
    service-registry:
      auto-multi-registration.enabled: true
      auto-registration:
        enabled: true
        fail-fast: true
management:
  endpoints:
    health.show-details: always
    web:
      base-path: /actuator
      exposure.include: health,info,env,prometheus,metrics,httptrace,threaddump,heapdump,springmetrics
  metrics:
    export.prometheus:
      descriptions: true
      enabled: true
      step: 1m
  server:
    servlet:
      context-path: /
  web.server.auto-time-requests: true
  health:
    NacosDiscovery:
      enabled: false
    elasticsearch:
      enabled: false
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000