server:
  port: 7767
  servlet:
    context-path: /test-gen
spring:
  application:
    name: mybatis-gen
  datasource:
    name: testerDS
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      poolName: Hikari
      auto-commit: false

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: off


knife4j:
  enable: true
  production: false
  documents:
    -
      group: test
      name: task
      locations: com.example.task.controller


logging:
  level:
    org:
      springframework:
        statemachine: debug