server:
  port: 7001

service-url:
  service-provider: http://cloud-provider


spring:
  application:
    name: cloud-consumer
  cloud:
    stream:
      bindings:
        input:
          destination: channelin2
          group: cloud-consumer
          consumer:
            enableDlq: true
            dlqName: ErrorTopic-listener
            autoCommitOffset: true
            concurrency: 7
        output:
          destination: order-topic