spring:
  cloud:
    gateway:
      discovery:
        locator:
          # 开启从注册中心动态创建路由的功能，利用微服务名称进行路由
          # 只要请求地址符合规则：http://gatewayip:gatewayport/微服务名称/微服务请求地址
          # 网关自动映射。把请求转发到 http://微服务名称/微服务请求地址
          enabled: true
      routes:
        - id: api-gateway-provider
          #uri: http://localhost:8001  #静态，写死了地址，只能调用一个服务
          uri: lb://cloud-provider  #动态，lb://微服务名
          predicates:
            - Path=/api/cloud-provider/**
          filters:
            - StripPrefix=1
        - id: api-gateway-consumer
          uri: lb://cloud-consumer
          predicates:
            - Path=/api/cloud-consumer/**
          filters:
            - StripPrefix=1