spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true               # 开启从注册中心动态创建路由的功能，利用微服务名称进行路由
      routes:
        - id: api-gateway-provider
           # 动态路由方式需要配合eureka、nacos注册中心使用
          uri: http://localhost:8083
          predicates:
            - Path=/api/provider/**
          filters:
            - StripPrefix=1
        - id: api-gateway-consumer
           # 动态路由方式需要配合eureka、nacos注册中心使用
          uri: http://localhost:8081
          predicates:
            - Path=/consumer/provider/**
          filters:
            - StripPrefix=1