server:
  port: 14000
spring:
  application:
    name: cloud-gateway
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        # 账号密码。 配置了要验证就一定要记得加这个配
        access-key: nacos
        secret-key: nacos
        namespace: ced8504b-967b-4e96-8d38-17f4349e4ab5
    gateway:
      discovery:
        locator:
          # 开启从注册中心动态创建路由的功能，利用微服务名称进行路由
          # 只要请求地址符合规则：http://gatewayip:gatewayport/微服务名称/微服务请求地址
          # 网关自动映射。把请求转发到 http://微服务名称/微服务请求地址
          enabled: false
      routes:
        - id: api-gateway-provider
          #uri: http://localhost:8001  #静态，写死了地址，只能调用一个服务
          uri: lb://cloud-provider  #动态，lb://微服务名
          predicates:
            - Path=/api/cloud-provider/**
          filters:
            - StripPrefix=1
        - id: api-gateway-consumer
          uri: lb://cloud-consumer
          predicates:
            - Path=/api/cloud-consumer/**
          filters:
            - StripPrefix=1
        - id: api-gateway-simple
          uri: http://127.0.0.1:7777
          predicates:
            - Path=/api/cloud-simple/**
          filters:
            - StripPrefix=1